trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  name: 'Default'

variables:
  nodeVersion: '22.22.3'

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '$(nodeVersion)'

- script: |
    cd frontend
    npm ci
  displayName: 'Install Frontend Dependencies'

- script: |
    cd frontend
    npm run build
  displayName: 'Build Angular Application'

- task: CopyFiles@2
  displayName: 'Prepare Frontend Artifact'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/frontend/dist/financial-trackerUI/browser'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Frontend Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/frontend'
    artifact: 'frontend'