trigger: none

resources:
  pipelines:
    - pipeline: backendCI
      source: 'Financial Tracker - Backend CI'
      trigger: none

    - pipeline: frontendCI
      source: 'Financial Tracker - Frontend CI'
      trigger: none

pool:
  name: 'Default'

variables:
  azureSubscription: 'FinancialTracker-ServiceConnection'
  appServiceName: 'financial-tracker-api-raj'

steps:

- download: backendCI
  artifact: backend
  displayName: 'Download Backend Artifact'

- download: frontendCI
  artifact: frontend
  displayName: 'Download Frontend Artifact'

- task: CopyFiles@2
  displayName: 'Copy Angular files to wwwroot'
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/frontendCI/frontend'
    Contents: '**'
    TargetFolder: '$(Pipeline.Workspace)/backendCI/backend/wwwroot'
    CleanTargetFolder: true

- task: AzureWebApp@1
  displayName: 'Deploy Financial Tracker to Azure'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appServiceName)'
    package: '$(Pipeline.Workspace)/backendCI/backend'