trigger: none

pool:
  name: 'Default'

resources:
  pipelines:
    - pipeline: backendCI
      source: 'Financial Tracker - Backend CI'
      trigger: none

    - pipeline: frontendCI
      source: 'Financial Tracker - Frontend CI'
      trigger: none

variables:
  azureSubscription: 'FinancialTracker-ServiceConnection'
  appName: 'financial-tracker-api-raj'

steps:

- task: DownloadPipelineArtifact@2
  displayName: 'Download Backend Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    definition: 'Financial Tracker - Backend CI'
    buildVersionToDownload: 'latest'
    artifactName: 'backend'
    targetPath: '$(Pipeline.Workspace)/backendCI'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Frontend Artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    definition: 'Financial Tracker - Frontend CI'
    buildVersionToDownload: 'latest'
    artifactName: 'frontend'
    targetPath: '$(Pipeline.Workspace)/frontendCI'

- task: CopyFiles@2
  displayName: 'Copy Angular files to wwwroot'
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/frontendCI'
    Contents: '**'
    TargetFolder: '$(Pipeline.Workspace)/backendCI/backend/wwwroot'
    CleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: 'Create Deployment Package'
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/backendCI/backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/financial-tracker.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy Financial Tracker'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/financial-tracker.zip'